# Generated by Django 4.1.6 on 2024-03-28 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofiles_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
