# Generated by Django 4.1.6 on 2024-08-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notifications_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='date',
            new_name='datetime',
        ),
    ]
