# Generated by Django 4.1.6 on 2024-07-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialregistries',
            name='id',
            field=models.UUIDField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
