# Generated by Django 4.1.6 on 2024-07-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_alter_trialregistries_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialregistries',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
