# Generated by Django 4.1.6 on 2024-07-12 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_alter_trialregistries_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialregistries',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RunSQL("ALTER TABLE trial_registries ALTER COLUMN date_added SET DEFAULT CURRENT_DATE;"),
    ]
