# Generated by Django 4.1.6 on 2025-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_alter_trialregistries_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'project_types',
                'ordering': ['id'],
            },
        ),
    ]
