# Generated by Django 4.1.6 on 2025-11-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0018_alter_dataaccessrequest_project_type'),
        ('context', '0005_projecttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
