# Generated by Django 4.1.6 on 2024-03-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_geogentities_name'),
        ('mdm', '0002_studies_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataobjects',
            name='organisation',
            field=models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_objects_organisation_id', to='general.organisations'),
        ),
        migrations.AlterField(
            model_name='studies',
            name='organisation',
            field=models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies_organisation_id', to='general.organisations'),
        ),
    ]
