# Generated by Django 4.1.6 on 2024-04-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0003_alter_dataobjects_access_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectrelationships',
            name='target_object_id',
        ),
        migrations.AddField(
            model_name='objectrelationships',
            name='target_object',
            field=models.ForeignKey(blank=True, db_column='target_object', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships_target_object', to='mdm.dataobjects'),
        ),
    ]
