# Generated by Django 4.1.6 on 2024-04-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0004_remove_objectrelationships_target_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyrelationships',
            name='target_study_id',
        ),
        migrations.AddField(
            model_name='studyrelationships',
            name='target_study',
            field=models.ForeignKey(blank=True, db_column='target_study', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_relationships_target_study', to='mdm.studies'),
        ),
    ]
