# Generated by Django 4.1.6 on 2024-06-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_objectnumberseq_studynumberseq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectNumberSeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.IntegerField()),
                ('increment_by', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('min_value', models.IntegerField()),
                ('cache_value', models.IntegerField()),
                ('log_cnt', models.IntegerField()),
                ('is_cycled', models.BooleanField()),
                ('is_called', models.BooleanField()),
            ],
            options={
                'db_table': 'object_number_seq',
            },
        ),
        migrations.CreateModel(
            name='StudyNumberSeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.IntegerField()),
                ('increment_by', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('min_value', models.IntegerField()),
                ('cache_value', models.IntegerField()),
                ('log_cnt', models.IntegerField()),
                ('is_cycled', models.BooleanField()),
                ('is_called', models.BooleanField()),
            ],
            options={
                'db_table': 'study_number_seq',
            },
        ),
    ]
