# Generated by Django 4.1.6 on 2024-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0008_objectnumberseq_studynumberseq'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataobjects',
            name='embargo_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
