# Generated by Django 4.1.6 on 2024-07-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0009_dataobjects_embargo_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectinstances',
            name='repository_org',
        ),
        migrations.AddField(
            model_name='objectinstances',
            name='repository',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
