# Generated by Django 4.1.6 on 2024-07-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0010_remove_objectinstances_repository_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinstances',
            name='repository',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
