# Generated by Django 4.1.6 on 2024-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0011_alter_objectinstances_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectcontributors',
            name='person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycontributors',
            name='person',
            field=models.TextField(blank=True, null=True),
        ),
    ]
