# Generated by Django 4.1.6 on 2024-07-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0012_alter_objectcontributors_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectinstances',
            old_name='object_id',
            new_name='data_object',
        ),
    ]
