# Generated by Django 4.1.6 on 2024-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0013_rename_object_id_objectinstances_data_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectinstances',
            name='sd_iid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
