# Generated by Django 4.1.6 on 2024-11-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0015_dataobjects_total_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectinstances',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
