# Generated by Django 4.1.6 on 2024-06-03 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtpobjects',
            old_name='object_id',
            new_name='data_object',
        ),
        migrations.RenameField(
            model_name='dtpprereqs',
            old_name='object_id',
            new_name='data_object',
        ),
        migrations.RenameField(
            model_name='dtpstudies',
            old_name='study_id',
            new_name='study',
        ),
        migrations.RenameField(
            model_name='dupobjects',
            old_name='object_id',
            new_name='data_object',
        ),
        migrations.RenameField(
            model_name='dupprereqs',
            old_name='object_id',
            new_name='data_object',
        ),
        migrations.RenameField(
            model_name='dupstudies',
            old_name='study_id',
            new_name='study',
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='provider_signatory_1',
            field=models.ForeignKey(db_column='provider_signatory_1', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dua_provider_signatory_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='provider_signatory_2',
            field=models.ForeignKey(db_column='provider_signatory_2', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dua_provider_signatory_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='repo_is_proxy_provider',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='repo_signatory_1',
            field=models.ForeignKey(db_column='repo_signatory_1', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dua_repo_signatory_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='repo_signatory_2',
            field=models.ForeignKey(db_column='repo_signatory_2', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dua_repo_signatory_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='requester_signatory_1',
            field=models.ForeignKey(db_column='requester_signatory_1', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dua_requester_signatory_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='requester_signatory_2',
            field=models.ForeignKey(db_column='requester_signatory_2', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dua_requester_signatory_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
