# Generated by Django 4.1.6 on 2024-06-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_rename_object_id_dtpobjects_data_object_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauseaccesses',
            old_name='provider_signatory_1',
            new_name='provider_signatory1',
        ),
        migrations.RenameField(
            model_name='datauseaccesses',
            old_name='provider_signatory_2',
            new_name='provider_signatory2',
        ),
        migrations.RenameField(
            model_name='datauseaccesses',
            old_name='repo_signatory_1',
            new_name='repo_signatory1',
        ),
        migrations.RenameField(
            model_name='datauseaccesses',
            old_name='repo_signatory_2',
            new_name='repo_signatory2',
        ),
        migrations.RenameField(
            model_name='datauseaccesses',
            old_name='requester_signatory_1',
            new_name='requester_signatory1',
        ),
        migrations.RenameField(
            model_name='datauseaccesses',
            old_name='requester_signatory_2',
            new_name='requester_signatory2',
        ),
    ]
