# Generated by Django 4.1.6 on 2024-06-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_rename_provider_signatory_1_datauseaccesses_provider_signatory1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtpprereqs',
            name='data_object',
        ),
        migrations.AddField(
            model_name='dtpprereqs',
            name='dtp_data_object',
            field=models.ForeignKey(blank=True, db_column='dtp_data_object', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_prereqs_object_id', to='rms.dtpobjects'),
        ),
    ]
