# Generated by Django 4.1.6 on 2024-06-10 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('rms', '0005_alter_datatransferaccesses_provider_signature1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransferaccesses',
            name='provider_signature1',
            field=models.ForeignKey(db_column='provider_signature_1', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dta_provider_signature_1', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='datatransferaccesses',
            name='provider_signature2',
            field=models.ForeignKey(db_column='provider_signature_2', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dta_provider_signature_2', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='datatransferaccesses',
            name='repo_signature1',
            field=models.ForeignKey(db_column='repo_signature_1', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dta_repo_signature_1', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='datatransferaccesses',
            name='repo_signature2',
            field=models.ForeignKey(db_column='repo_signature_2', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dta_repo_signature_2', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='provider_signatory1',
            field=models.ForeignKey(db_column='provider_signatory_1', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_provider_signatory_1', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='provider_signatory2',
            field=models.ForeignKey(db_column='provider_signatory_2', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_provider_signatory_2', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='repo_signatory1',
            field=models.ForeignKey(db_column='repo_signatory_1', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_repo_signatory_1', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='repo_signatory2',
            field=models.ForeignKey(db_column='repo_signatory_2', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_repo_signatory_2', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='requester_signatory1',
            field=models.ForeignKey(db_column='requester_signatory_1', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_requester_signatory_1', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='requester_signatory2',
            field=models.ForeignKey(db_column='requester_signatory_2', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_requester_signatory_2', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='access_check_by',
            field=models.ForeignKey(blank=True, db_column='access_check_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects_access_check_by', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='access_check_status',
            field=models.ForeignKey(blank=True, db_column='access_check_status_id', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects_access_check_status_id', to='context.checkstatustypes'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='access_type',
            field=models.ForeignKey(blank=True, db_column='access_type_id', default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects_access_type_id', to='context.objectaccesstypes'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='md_check_by',
            field=models.ForeignKey(blank=True, db_column='md_check_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects_md_check_by', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='md_check_status',
            field=models.ForeignKey(blank=True, db_column='md_check_status_id', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects_md_check_status_id', to='context.checkstatustypes'),
        ),
    ]
