# Generated by Django 4.1.6 on 2024-06-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0006_alter_datatransferaccesses_provider_signature1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauseaccesses',
            name='provider_signatory1',
            field=models.ForeignKey(db_column='provider_signatory_1', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_provider_signatory_1', to='rms.duppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='provider_signatory2',
            field=models.ForeignKey(db_column='provider_signatory_2', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_provider_signatory_2', to='rms.duppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='repo_signatory1',
            field=models.ForeignKey(db_column='repo_signatory_1', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_repo_signatory_1', to='rms.duppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='repo_signatory2',
            field=models.ForeignKey(db_column='repo_signatory_2', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_repo_signatory_2', to='rms.duppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='requester_signatory1',
            field=models.ForeignKey(db_column='requester_signatory_1', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_requester_signatory_1', to='rms.duppeople'),
        ),
        migrations.AlterField(
            model_name='datauseaccesses',
            name='requester_signatory2',
            field=models.ForeignKey(db_column='requester_signatory_2', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dua_requester_signatory_2', to='rms.duppeople'),
        ),
    ]
