# Generated by Django 4.1.6 on 2024-06-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0007_alter_datauseaccesses_provider_signatory1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatransferprocesses',
            old_name='initial_contact_date',
            new_name='set_up_start_date',
        ),
        migrations.RemoveField(
            model_name='datatransferprocesses',
            name='availability_confirmed_date',
        ),
        migrations.RemoveField(
            model_name='datatransferprocesses',
            name='availability_requested_date',
        ),
        migrations.RemoveField(
            model_name='datatransferprocesses',
            name='md_access_granted_date',
        ),
        migrations.RemoveField(
            model_name='datatransferprocesses',
            name='md_integrated_with_mdr_date',
        ),
    ]
