# Generated by Django 4.1.6 on 2024-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0010_rename_access_confirmed_date_datauseprocesses_availability_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauseprocesses',
            name='secondary_use_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
