# Generated by Django 4.1.6 on 2024-07-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0011_datauseprocesses_secondary_use_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauseprocesses',
            name='secondary_use_reason',
        ),
        migrations.AddField(
            model_name='datauseaccesses',
            name='secondary_use_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
