# Generated by Django 4.1.6 on 2024-11-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0012_remove_datauseprocesses_secondary_use_reason_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataTransferAccesses',
            new_name='DataTransferAgreements',
        ),
    ]
