# Generated by Django 4.1.6 on 2025-11-14 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0002_organisations_manual_entry'),
        ('mdm', '0016_objectinstances_title'),
        ('context', '0005_projecttype'),
        ('rms', '0014_rename_datauseaccesses_datauseagreements'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cv_path', models.CharField(max_length=255, null=True)),
                ('project_title', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('project_abstract', models.TextField(blank=True, null=True)),
                ('ethics_approval', models.CharField(blank=True, max_length=30, null=True)),
                ('ethics_approval_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('funding', models.CharField(blank=True, max_length=1000, null=True)),
                ('estimated_access_duration_required', models.CharField(blank=True, max_length=255, null=True)),
                ('provisional_starting_date', models.DateField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('additional_secondary_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, db_column='organisation_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_requests', to='general.organisations')),
                ('principal_secondary_user', models.ForeignKey(blank=True, db_column='secondary_user_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_requests', to=settings.AUTH_USER_MODEL)),
                ('project_type', models.ForeignKey(blank=True, db_column='project_type_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_requests', to='context.projecttype')),
                ('requested_study', models.ForeignKey(blank=True, db_column='requested_study_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_requests', to='mdm.studies')),
            ],
            options={
                'db_table': 'data_access_requests',
                'ordering': ['created_on'],
            },
        ),
    ]
