# Generated by Django 4.1.6 on 2025-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0015_dataaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccessrequest',
            name='organisation_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
