# Generated by Django 4.1.6 on 2025-11-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0016_dataaccessrequest_organisation_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataaccessrequest',
            old_name='funding',
            new_name='project_funding',
        ),
    ]
