# Generated by Django 4.1.6 on 2025-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0017_rename_funding_dataaccessrequest_project_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccessrequest',
            name='project_type',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
