# Generated by Django 4.1.6 on 2025-11-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0018_alter_dataaccessrequest_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataaccessrequest',
            options={'ordering': ['id']},
        ),
    ]
