# Generated by Django 4.1.6 on 2025-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0019_alter_dataaccessrequest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataaccessrequest',
            name='cv_path',
        ),
        migrations.AddField(
            model_name='dataaccessrequest',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
