# Generated by Django 4.1.6 on 2025-11-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0020_remove_dataaccessrequest_cv_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccessrequest',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
