# Generated by Django 4.1.6 on 2025-11-21 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rms', '0021_alter_dataaccessrequest_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccessrequest',
            name='additional_secondary_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
