# Generated by Django 4.1.6 on 2025-11-28 09:39

from django.db import migrations, models
import rms.models.dup.data_access_request


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0022_alter_dataaccessrequest_additional_secondary_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccessrequest',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=rms.models.dup.data_access_request.get_cv_path),
        ),
    ]
