# Generated by Django 4.1.6 on 2025-12-01 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_organisations_manual_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('context', '0006_delete_projecttype'),
        ('rms', '0023_alter_dataaccessrequest_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauseprocesses',
            name='data_access_request',
            field=models.ForeignKey(blank=True, db_column='data_access_request_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dup_id', to='rms.dataaccessrequest'),
        ),
        migrations.AlterField(
            model_name='dataaccessrequest',
            name='additional_secondary_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datauseprocesses',
            name='organisation',
            field=models.ForeignKey(blank=True, db_column='org_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation', to='general.organisations'),
        ),
        migrations.AlterField(
            model_name='datauseprocesses',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dup_status_id', to='context.dupstatustypes'),
        ),
    ]
