# Generated by Django 4.1.6 on 2025-12-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0024_datauseprocesses_data_access_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauseprocesses',
            old_name='prereqs_met_date',
            new_name='request_decision_date',
        ),
        migrations.RemoveField(
            model_name='datauseprocesses',
            name='set_up_start_date',
        ),
    ]
