# Generated by Django 4.1.6 on 2025-12-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0025_rename_prereqs_met_date_datauseprocesses_request_decision_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauseprocesses',
            old_name='dua_agreed_date',
            new_name='agreement_signed_date',
        ),
        migrations.RenameField(
            model_name='datauseprocesses',
            old_name='availability_expiry_date',
            new_name='availability_end_date',
        ),
        migrations.RenameField(
            model_name='datauseprocesses',
            old_name='availability_requested_date',
            new_name='availability_start_date',
        ),
        migrations.RemoveField(
            model_name='datauseprocesses',
            name='set_up_complete_date',
        ),
    ]
