# Generated by Django 4.1.6 on 2025-12-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0026_rename_dua_agreed_date_datauseprocesses_agreement_signed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauseprocesses',
            old_name='availability_start_date',
            new_name='data_access_available_from',
        ),
        migrations.RenameField(
            model_name='datauseprocesses',
            old_name='availability_end_date',
            new_name='data_access_available_until',
        ),
    ]
