# Generated by Django 4.1.6 on 2025-12-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0027_rename_availability_start_date_datauseprocesses_data_access_available_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauseagreements',
            old_name='repo_is_proxy_provider',
            new_name='access_requests_delegated_to_crdsr',
        ),
        migrations.RenameField(
            model_name='datauseagreements',
            old_name='dua_file_path',
            new_name='agreement_link',
        ),
        migrations.RenameField(
            model_name='datauseagreements',
            old_name='variations',
            new_name='variations_from_agreement_template',
        ),
        migrations.RemoveField(
            model_name='datauseagreements',
            name='conforms_to_default',
        ),
        migrations.RemoveField(
            model_name='datauseagreements',
            name='secondary_use_reason',
        ),
    ]
