# Generated by Django 4.1.6 on 2025-12-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0016_objectinstances_title'),
        ('context', '0006_delete_projecttype'),
        ('rms', '0028_rename_repo_is_proxy_provider_datauseagreements_access_requests_delegated_to_crdsr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dupobjects',
            name='access_type',
            field=models.ForeignKey(blank=True, db_column='access_type_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_objects', to='context.accessprereqtypes'),
        ),
        migrations.AlterField(
            model_name='dupobjects',
            name='data_object',
            field=models.ForeignKey(blank=True, db_column='object_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_objects', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='dupobjects',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_objects', to='rms.datauseprocesses'),
        ),
        migrations.AlterField(
            model_name='dupstudies',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_studies', to='rms.datauseprocesses'),
        ),
        migrations.AlterField(
            model_name='dupstudies',
            name='study',
            field=models.ForeignKey(blank=True, db_column='study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_studies', to='mdm.studies'),
        ),
    ]
