# Generated by Django 4.1.6 on 2025-12-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0029_alter_dupobjects_access_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupobjects',
            name='dup_study',
            field=models.ForeignKey(blank=True, db_column='dup_study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_objects', to='rms.dupstudies'),
        ),
    ]
