# Generated by Django 4.1.6 on 2025-12-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0016_objectinstances_title'),
        ('rms', '0030_dupobjects_dup_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtpobjects',
            name='dtp_study',
            field=models.ForeignKey(blank=True, db_column='dup_study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects', to='rms.dtpstudies'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='data_object',
            field=models.ForeignKey(blank=True, db_column='object_id', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects', to='mdm.dataobjects'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='dtp_id',
            field=models.ForeignKey(blank=True, db_column='dtp_id', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects', to='rms.datatransferprocesses'),
        ),
    ]
