# Generated by Django 4.1.6 on 2025-12-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0006_delete_projecttype'),
        ('rms', '0031_dtpobjects_dtp_study_alter_dtpobjects_data_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtpobjects',
            name='access_type',
            field=models.ForeignKey(blank=True, db_column='access_type_id', default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects', to='context.objectaccesstypes'),
        ),
    ]
