# Generated by Django 4.1.6 on 2025-12-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0033_alter_dtpobjects_access_check_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtpobjects',
            name='md_check_by',
            field=models.ForeignKey(blank=True, db_column='md_check_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects', to='rms.dtppeople'),
        ),
    ]
