# Generated by Django 4.1.6 on 2025-12-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0006_delete_projecttype'),
        ('rms', '0034_alter_dtpobjects_md_check_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtpobjects',
            name='access_check_by',
            field=models.ForeignKey(blank=True, db_column='access_check_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='dtp_study',
            field=models.ForeignKey(blank=True, db_column='dtp_study_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtp_objects', to='rms.dtpstudies'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='md_check_by',
            field=models.ForeignKey(blank=True, db_column='md_check_by', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects_md_check', to='rms.dtppeople'),
        ),
        migrations.AlterField(
            model_name='dtpobjects',
            name='md_check_status',
            field=models.ForeignKey(blank=True, db_column='md_check_status_id', default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dtp_objects_md_check', to='context.checkstatustypes'),
        ),
    ]
