# Generated by Django 4.1.6 on 2025-12-15 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0035_alter_dtpobjects_access_check_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccessrequest',
            name='request_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
