# Generated by Django 4.1.6 on 2025-12-15 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rms', '0036_dataaccessrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duppeople',
            name='dup_id',
            field=models.ForeignKey(blank=True, db_column='dup_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_people', to='rms.datauseprocesses'),
        ),
        migrations.AlterField(
            model_name='duppeople',
            name='person',
            field=models.ForeignKey(blank=True, db_column='person_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_people', to=settings.AUTH_USER_MODEL),
        ),
    ]
