# Generated by Django 4.1.6 on 2025-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='manual_entry',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
